name: Ejecutar index.js cada 5 minutos

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  run-node-script:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: message
        run: echo "${{ vars.HOLA }}, Hola mundo"

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"  # Usa la versión que necesites
          cache: "npm"

      - name: Instalar dependencias (si hay package.json)
        run: |
          if [ -f package.json ]; then
            npm install
          fi

      - name: Ejecutar método con parámetro
        run: node -e 'require("./index").miMetodo("${{ vars.HOLA }}")'
