name: Ejecutar Express y hacer un GET

on:
  # schedule:
  #   - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  test-express:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Instalar dependencias
        run: npm install

      - name: Iniciar servidor Express en segundo plano
        run: npm start &

      - name: Esperar a que el servidor esté listo
        run: sleep 5

      - name: Hacer petición GET a Express
        run: curl -i http://localhost:3000

      - name: Finalizar procesos en segundo plano
        run: kill $(lsof -t -i:3000) || true
